# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='ledx2xn_ec_shm.proto',
  package='',
  serialized_pb='\n\x14ledx2xn_ec_shm.proto\x1a\x14\x63omponent_base.proto\"A\n\x14M3LedX2XNEcShmStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x0c\n\x04test\x18\x02 \x01(\x01\"%\n\x15M3LedX2XNEcShmCommand\x12\x0c\n\x04test\x18\x01 \x01(\x01\"#\n\x13M3LedX2XNEcShmParam\x12\x0c\n\x04test\x18\x01 \x01(\x01\x42\x02H\x01')




_M3LEDX2XNECSHMSTATUS = descriptor.Descriptor(
  name='M3LedX2XNEcShmStatus',
  full_name='M3LedX2XNEcShmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LedX2XNEcShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedX2XNEcShmStatus.test', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=111,
)


_M3LEDX2XNECSHMCOMMAND = descriptor.Descriptor(
  name='M3LedX2XNEcShmCommand',
  full_name='M3LedX2XNEcShmCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedX2XNEcShmCommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=150,
)


_M3LEDX2XNECSHMPARAM = descriptor.Descriptor(
  name='M3LedX2XNEcShmParam',
  full_name='M3LedX2XNEcShmParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedX2XNEcShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=187,
)

_M3LEDX2XNECSHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3LedX2XNEcShmStatus'] = _M3LEDX2XNECSHMSTATUS
DESCRIPTOR.message_types_by_name['M3LedX2XNEcShmCommand'] = _M3LEDX2XNECSHMCOMMAND
DESCRIPTOR.message_types_by_name['M3LedX2XNEcShmParam'] = _M3LEDX2XNECSHMPARAM

class M3LedX2XNEcShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECSHMSTATUS
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcShmStatus)

class M3LedX2XNEcShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECSHMCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcShmCommand)

class M3LedX2XNEcShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECSHMPARAM
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcShmParam)

# @@protoc_insertion_point(module_scope)
