// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "joint_mode_ros.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* JOINT_MODE_ROS_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_joint_5fmode_5fros_2eproto() {
  protobuf_AddDesc_joint_5fmode_5fros_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "joint_mode_ros.proto");
  GOOGLE_CHECK(file != NULL);
  JOINT_MODE_ROS_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_joint_5fmode_5fros_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_joint_5fmode_5fros_2eproto() {
}

void protobuf_AddDesc_joint_5fmode_5fros_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024joint_mode_ros.proto*\261\001\n\016JOINT_MODE_RO"
    "S\022\026\n\022JOINT_MODE_ROS_OFF\020\000\022\030\n\024JOINT_MODE_"
    "ROS_THETA\020\001\022\033\n\027JOINT_MODE_ROS_THETA_GC\020\002"
    "\022\034\n\030JOINT_MODE_ROS_TORQUE_GC\020\003\022\027\n\023JOINT_"
    "MODE_ROS_POSE\020\004\022\031\n\025JOINT_MODE_ROS_TORQUE"
    "\020\005B\002H\001", 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "joint_mode_ros.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_joint_5fmode_5fros_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_joint_5fmode_5fros_2eproto {
  StaticDescriptorInitializer_joint_5fmode_5fros_2eproto() {
    protobuf_AddDesc_joint_5fmode_5fros_2eproto();
  }
} static_descriptor_initializer_joint_5fmode_5fros_2eproto_;

const ::google::protobuf::EnumDescriptor* JOINT_MODE_ROS_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JOINT_MODE_ROS_descriptor_;
}
bool JOINT_MODE_ROS_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
