// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "led_matrix_ec_shm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* M3LedMatrixEcShmStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3LedMatrixEcShmStatus_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3LedMatrixEcShmCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3LedMatrixEcShmCommand_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3LedMatrixEcShmParam_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3LedMatrixEcShmParam_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_led_5fmatrix_5fec_5fshm_2eproto() {
  protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "led_matrix_ec_shm.proto");
  GOOGLE_CHECK(file != NULL);
  M3LedMatrixEcShmStatus_descriptor_ = file->message_type(0);
  static const int M3LedMatrixEcShmStatus_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmStatus, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmStatus, test_),
  };
  M3LedMatrixEcShmStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3LedMatrixEcShmStatus_descriptor_,
      M3LedMatrixEcShmStatus::default_instance_,
      M3LedMatrixEcShmStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3LedMatrixEcShmStatus));
  M3LedMatrixEcShmCommand_descriptor_ = file->message_type(1);
  static const int M3LedMatrixEcShmCommand_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmCommand, test_),
  };
  M3LedMatrixEcShmCommand_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3LedMatrixEcShmCommand_descriptor_,
      M3LedMatrixEcShmCommand::default_instance_,
      M3LedMatrixEcShmCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmCommand, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmCommand, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3LedMatrixEcShmCommand));
  M3LedMatrixEcShmParam_descriptor_ = file->message_type(2);
  static const int M3LedMatrixEcShmParam_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmParam, test_),
  };
  M3LedMatrixEcShmParam_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3LedMatrixEcShmParam_descriptor_,
      M3LedMatrixEcShmParam::default_instance_,
      M3LedMatrixEcShmParam_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmParam, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3LedMatrixEcShmParam, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3LedMatrixEcShmParam));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_led_5fmatrix_5fec_5fshm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3LedMatrixEcShmStatus_descriptor_, &M3LedMatrixEcShmStatus::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3LedMatrixEcShmCommand_descriptor_, &M3LedMatrixEcShmCommand::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3LedMatrixEcShmParam_descriptor_, &M3LedMatrixEcShmParam::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_led_5fmatrix_5fec_5fshm_2eproto() {
  delete M3LedMatrixEcShmStatus::default_instance_;
  delete M3LedMatrixEcShmStatus_reflection_;
  delete M3LedMatrixEcShmCommand::default_instance_;
  delete M3LedMatrixEcShmCommand_reflection_;
  delete M3LedMatrixEcShmParam::default_instance_;
  delete M3LedMatrixEcShmParam_reflection_;
}

void protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_component_5fbase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027led_matrix_ec_shm.proto\032\024component_bas"
    "e.proto\"C\n\026M3LedMatrixEcShmStatus\022\033\n\004bas"
    "e\030\001 \001(\0132\r.M3BaseStatus\022\014\n\004test\030\002 \001(\001\"\'\n\027"
    "M3LedMatrixEcShmCommand\022\014\n\004test\030\001 \001(\001\"%\n"
    "\025M3LedMatrixEcShmParam\022\014\n\004test\030\001 \001(\001B\002H\001", 200);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "led_matrix_ec_shm.proto", &protobuf_RegisterTypes);
  M3LedMatrixEcShmStatus::default_instance_ = new M3LedMatrixEcShmStatus();
  M3LedMatrixEcShmCommand::default_instance_ = new M3LedMatrixEcShmCommand();
  M3LedMatrixEcShmParam::default_instance_ = new M3LedMatrixEcShmParam();
  M3LedMatrixEcShmStatus::default_instance_->InitAsDefaultInstance();
  M3LedMatrixEcShmCommand::default_instance_->InitAsDefaultInstance();
  M3LedMatrixEcShmParam::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_led_5fmatrix_5fec_5fshm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_led_5fmatrix_5fec_5fshm_2eproto {
  StaticDescriptorInitializer_led_5fmatrix_5fec_5fshm_2eproto() {
    protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto();
  }
} static_descriptor_initializer_led_5fmatrix_5fec_5fshm_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int M3LedMatrixEcShmStatus::kBaseFieldNumber;
const int M3LedMatrixEcShmStatus::kTestFieldNumber;
#endif  // !_MSC_VER

M3LedMatrixEcShmStatus::M3LedMatrixEcShmStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3LedMatrixEcShmStatus::InitAsDefaultInstance() {
  base_ = const_cast< ::M3BaseStatus*>(&::M3BaseStatus::default_instance());
}

M3LedMatrixEcShmStatus::M3LedMatrixEcShmStatus(const M3LedMatrixEcShmStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3LedMatrixEcShmStatus::SharedCtor() {
  _cached_size_ = 0;
  base_ = NULL;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3LedMatrixEcShmStatus::~M3LedMatrixEcShmStatus() {
  SharedDtor();
}

void M3LedMatrixEcShmStatus::SharedDtor() {
  if (this != default_instance_) {
    delete base_;
  }
}

void M3LedMatrixEcShmStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3LedMatrixEcShmStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3LedMatrixEcShmStatus_descriptor_;
}

const M3LedMatrixEcShmStatus& M3LedMatrixEcShmStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto();  return *default_instance_;
}

M3LedMatrixEcShmStatus* M3LedMatrixEcShmStatus::default_instance_ = NULL;

M3LedMatrixEcShmStatus* M3LedMatrixEcShmStatus::New() const {
  return new M3LedMatrixEcShmStatus;
}

void M3LedMatrixEcShmStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_base()) {
      if (base_ != NULL) base_->::M3BaseStatus::Clear();
    }
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3LedMatrixEcShmStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .M3BaseStatus base = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_test;
        break;
      }
      
      // optional double test = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_test:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3LedMatrixEcShmStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }
  
  // optional double test = 2;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3LedMatrixEcShmStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }
  
  // optional double test = 2;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3LedMatrixEcShmStatus::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .M3BaseStatus base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }
    
    // optional double test = 2;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3LedMatrixEcShmStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3LedMatrixEcShmStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3LedMatrixEcShmStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3LedMatrixEcShmStatus::MergeFrom(const M3LedMatrixEcShmStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::M3BaseStatus::MergeFrom(from.base());
    }
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3LedMatrixEcShmStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3LedMatrixEcShmStatus::CopyFrom(const M3LedMatrixEcShmStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3LedMatrixEcShmStatus::IsInitialized() const {
  
  return true;
}

void M3LedMatrixEcShmStatus::Swap(M3LedMatrixEcShmStatus* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3LedMatrixEcShmStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3LedMatrixEcShmStatus_descriptor_;
  metadata.reflection = M3LedMatrixEcShmStatus_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3LedMatrixEcShmCommand::kTestFieldNumber;
#endif  // !_MSC_VER

M3LedMatrixEcShmCommand::M3LedMatrixEcShmCommand()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3LedMatrixEcShmCommand::InitAsDefaultInstance() {
}

M3LedMatrixEcShmCommand::M3LedMatrixEcShmCommand(const M3LedMatrixEcShmCommand& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3LedMatrixEcShmCommand::SharedCtor() {
  _cached_size_ = 0;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3LedMatrixEcShmCommand::~M3LedMatrixEcShmCommand() {
  SharedDtor();
}

void M3LedMatrixEcShmCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3LedMatrixEcShmCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3LedMatrixEcShmCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3LedMatrixEcShmCommand_descriptor_;
}

const M3LedMatrixEcShmCommand& M3LedMatrixEcShmCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto();  return *default_instance_;
}

M3LedMatrixEcShmCommand* M3LedMatrixEcShmCommand::default_instance_ = NULL;

M3LedMatrixEcShmCommand* M3LedMatrixEcShmCommand::New() const {
  return new M3LedMatrixEcShmCommand;
}

void M3LedMatrixEcShmCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3LedMatrixEcShmCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double test = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3LedMatrixEcShmCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double test = 1;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3LedMatrixEcShmCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double test = 1;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3LedMatrixEcShmCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double test = 1;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3LedMatrixEcShmCommand::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3LedMatrixEcShmCommand* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3LedMatrixEcShmCommand*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3LedMatrixEcShmCommand::MergeFrom(const M3LedMatrixEcShmCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3LedMatrixEcShmCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3LedMatrixEcShmCommand::CopyFrom(const M3LedMatrixEcShmCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3LedMatrixEcShmCommand::IsInitialized() const {
  
  return true;
}

void M3LedMatrixEcShmCommand::Swap(M3LedMatrixEcShmCommand* other) {
  if (other != this) {
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3LedMatrixEcShmCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3LedMatrixEcShmCommand_descriptor_;
  metadata.reflection = M3LedMatrixEcShmCommand_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3LedMatrixEcShmParam::kTestFieldNumber;
#endif  // !_MSC_VER

M3LedMatrixEcShmParam::M3LedMatrixEcShmParam()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3LedMatrixEcShmParam::InitAsDefaultInstance() {
}

M3LedMatrixEcShmParam::M3LedMatrixEcShmParam(const M3LedMatrixEcShmParam& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3LedMatrixEcShmParam::SharedCtor() {
  _cached_size_ = 0;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3LedMatrixEcShmParam::~M3LedMatrixEcShmParam() {
  SharedDtor();
}

void M3LedMatrixEcShmParam::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3LedMatrixEcShmParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3LedMatrixEcShmParam::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3LedMatrixEcShmParam_descriptor_;
}

const M3LedMatrixEcShmParam& M3LedMatrixEcShmParam::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_led_5fmatrix_5fec_5fshm_2eproto();  return *default_instance_;
}

M3LedMatrixEcShmParam* M3LedMatrixEcShmParam::default_instance_ = NULL;

M3LedMatrixEcShmParam* M3LedMatrixEcShmParam::New() const {
  return new M3LedMatrixEcShmParam;
}

void M3LedMatrixEcShmParam::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3LedMatrixEcShmParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double test = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3LedMatrixEcShmParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double test = 1;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3LedMatrixEcShmParam::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double test = 1;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3LedMatrixEcShmParam::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double test = 1;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3LedMatrixEcShmParam::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3LedMatrixEcShmParam* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3LedMatrixEcShmParam*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3LedMatrixEcShmParam::MergeFrom(const M3LedMatrixEcShmParam& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3LedMatrixEcShmParam::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3LedMatrixEcShmParam::CopyFrom(const M3LedMatrixEcShmParam& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3LedMatrixEcShmParam::IsInitialized() const {
  
  return true;
}

void M3LedMatrixEcShmParam::Swap(M3LedMatrixEcShmParam* other) {
  if (other != this) {
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3LedMatrixEcShmParam::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3LedMatrixEcShmParam_descriptor_;
  metadata.reflection = M3LedMatrixEcShmParam_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
