// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tactile_pps22_ec.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* M3TactilePPS22EcStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3TactilePPS22EcStatus_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3TactilePPS22EcCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3TactilePPS22EcCommand_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3TactilePPS22EcParam_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3TactilePPS22EcParam_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_tactile_5fpps22_5fec_2eproto() {
  protobuf_AddDesc_tactile_5fpps22_5fec_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tactile_pps22_ec.proto");
  GOOGLE_CHECK(file != NULL);
  M3TactilePPS22EcStatus_descriptor_ = file->message_type(0);
  static const int M3TactilePPS22EcStatus_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, ethercat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, taxels_),
  };
  M3TactilePPS22EcStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3TactilePPS22EcStatus_descriptor_,
      M3TactilePPS22EcStatus::default_instance_,
      M3TactilePPS22EcStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3TactilePPS22EcStatus));
  M3TactilePPS22EcCommand_descriptor_ = file->message_type(1);
  static const int M3TactilePPS22EcCommand_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcCommand, dummy_),
  };
  M3TactilePPS22EcCommand_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3TactilePPS22EcCommand_descriptor_,
      M3TactilePPS22EcCommand::default_instance_,
      M3TactilePPS22EcCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcCommand, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcCommand, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3TactilePPS22EcCommand));
  M3TactilePPS22EcParam_descriptor_ = file->message_type(2);
  static const int M3TactilePPS22EcParam_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcParam, config_),
  };
  M3TactilePPS22EcParam_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3TactilePPS22EcParam_descriptor_,
      M3TactilePPS22EcParam::default_instance_,
      M3TactilePPS22EcParam_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcParam, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3TactilePPS22EcParam, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3TactilePPS22EcParam));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tactile_5fpps22_5fec_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3TactilePPS22EcStatus_descriptor_, &M3TactilePPS22EcStatus::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3TactilePPS22EcCommand_descriptor_, &M3TactilePPS22EcCommand::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3TactilePPS22EcParam_descriptor_, &M3TactilePPS22EcParam::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tactile_5fpps22_5fec_2eproto() {
  delete M3TactilePPS22EcStatus::default_instance_;
  delete M3TactilePPS22EcStatus_reflection_;
  delete M3TactilePPS22EcCommand::default_instance_;
  delete M3TactilePPS22EcCommand_reflection_;
  delete M3TactilePPS22EcParam::default_instance_;
  delete M3TactilePPS22EcParam_reflection_;
}

void protobuf_AddDesc_tactile_5fpps22_5fec_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_component_5fbase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026tactile_pps22_ec.proto\032\024component_base"
    ".proto\"}\n\026M3TactilePPS22EcStatus\022\033\n\004base"
    "\030\001 \001(\0132\r.M3BaseStatus\022#\n\010ethercat\030\002 \001(\0132"
    "\021.M3EtherCATStatus\022\021\n\ttimestamp\030\003 \001(\004\022\016\n"
    "\006taxels\030\004 \003(\005\"(\n\027M3TactilePPS22EcCommand"
    "\022\r\n\005dummy\030\001 \001(\005\"\'\n\025M3TactilePPS22EcParam"
    "\022\016\n\006config\030\001 \001(\005B\002H\001", 260);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tactile_pps22_ec.proto", &protobuf_RegisterTypes);
  M3TactilePPS22EcStatus::default_instance_ = new M3TactilePPS22EcStatus();
  M3TactilePPS22EcCommand::default_instance_ = new M3TactilePPS22EcCommand();
  M3TactilePPS22EcParam::default_instance_ = new M3TactilePPS22EcParam();
  M3TactilePPS22EcStatus::default_instance_->InitAsDefaultInstance();
  M3TactilePPS22EcCommand::default_instance_->InitAsDefaultInstance();
  M3TactilePPS22EcParam::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tactile_5fpps22_5fec_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tactile_5fpps22_5fec_2eproto {
  StaticDescriptorInitializer_tactile_5fpps22_5fec_2eproto() {
    protobuf_AddDesc_tactile_5fpps22_5fec_2eproto();
  }
} static_descriptor_initializer_tactile_5fpps22_5fec_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int M3TactilePPS22EcStatus::kBaseFieldNumber;
const int M3TactilePPS22EcStatus::kEthercatFieldNumber;
const int M3TactilePPS22EcStatus::kTimestampFieldNumber;
const int M3TactilePPS22EcStatus::kTaxelsFieldNumber;
#endif  // !_MSC_VER

M3TactilePPS22EcStatus::M3TactilePPS22EcStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3TactilePPS22EcStatus::InitAsDefaultInstance() {
  base_ = const_cast< ::M3BaseStatus*>(&::M3BaseStatus::default_instance());
  ethercat_ = const_cast< ::M3EtherCATStatus*>(&::M3EtherCATStatus::default_instance());
}

M3TactilePPS22EcStatus::M3TactilePPS22EcStatus(const M3TactilePPS22EcStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3TactilePPS22EcStatus::SharedCtor() {
  _cached_size_ = 0;
  base_ = NULL;
  ethercat_ = NULL;
  timestamp_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3TactilePPS22EcStatus::~M3TactilePPS22EcStatus() {
  SharedDtor();
}

void M3TactilePPS22EcStatus::SharedDtor() {
  if (this != default_instance_) {
    delete base_;
    delete ethercat_;
  }
}

void M3TactilePPS22EcStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3TactilePPS22EcStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3TactilePPS22EcStatus_descriptor_;
}

const M3TactilePPS22EcStatus& M3TactilePPS22EcStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tactile_5fpps22_5fec_2eproto();  return *default_instance_;
}

M3TactilePPS22EcStatus* M3TactilePPS22EcStatus::default_instance_ = NULL;

M3TactilePPS22EcStatus* M3TactilePPS22EcStatus::New() const {
  return new M3TactilePPS22EcStatus;
}

void M3TactilePPS22EcStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_base()) {
      if (base_ != NULL) base_->::M3BaseStatus::Clear();
    }
    if (has_ethercat()) {
      if (ethercat_ != NULL) ethercat_->::M3EtherCATStatus::Clear();
    }
    timestamp_ = GOOGLE_ULONGLONG(0);
  }
  taxels_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3TactilePPS22EcStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .M3BaseStatus base = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_ethercat;
        break;
      }
      
      // optional .M3EtherCATStatus ethercat = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ethercat:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ethercat()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_timestamp;
        break;
      }
      
      // optional uint64 timestamp = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_taxels;
        break;
      }
      
      // repeated int32 taxels = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_taxels:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_taxels())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_taxels())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_taxels;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3TactilePPS22EcStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }
  
  // optional .M3EtherCATStatus ethercat = 2;
  if (has_ethercat()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->ethercat(), output);
  }
  
  // optional uint64 timestamp = 3;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->timestamp(), output);
  }
  
  // repeated int32 taxels = 4;
  for (int i = 0; i < this->taxels_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->taxels(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3TactilePPS22EcStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }
  
  // optional .M3EtherCATStatus ethercat = 2;
  if (has_ethercat()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->ethercat(), target);
  }
  
  // optional uint64 timestamp = 3;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->timestamp(), target);
  }
  
  // repeated int32 taxels = 4;
  for (int i = 0; i < this->taxels_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->taxels(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3TactilePPS22EcStatus::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .M3BaseStatus base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }
    
    // optional .M3EtherCATStatus ethercat = 2;
    if (has_ethercat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ethercat());
    }
    
    // optional uint64 timestamp = 3;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->timestamp());
    }
    
  }
  // repeated int32 taxels = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->taxels_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->taxels(i));
    }
    total_size += 1 * this->taxels_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3TactilePPS22EcStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3TactilePPS22EcStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3TactilePPS22EcStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3TactilePPS22EcStatus::MergeFrom(const M3TactilePPS22EcStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  taxels_.MergeFrom(from.taxels_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::M3BaseStatus::MergeFrom(from.base());
    }
    if (from.has_ethercat()) {
      mutable_ethercat()->::M3EtherCATStatus::MergeFrom(from.ethercat());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3TactilePPS22EcStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3TactilePPS22EcStatus::CopyFrom(const M3TactilePPS22EcStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3TactilePPS22EcStatus::IsInitialized() const {
  
  return true;
}

void M3TactilePPS22EcStatus::Swap(M3TactilePPS22EcStatus* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(ethercat_, other->ethercat_);
    std::swap(timestamp_, other->timestamp_);
    taxels_.Swap(&other->taxels_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3TactilePPS22EcStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3TactilePPS22EcStatus_descriptor_;
  metadata.reflection = M3TactilePPS22EcStatus_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3TactilePPS22EcCommand::kDummyFieldNumber;
#endif  // !_MSC_VER

M3TactilePPS22EcCommand::M3TactilePPS22EcCommand()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3TactilePPS22EcCommand::InitAsDefaultInstance() {
}

M3TactilePPS22EcCommand::M3TactilePPS22EcCommand(const M3TactilePPS22EcCommand& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3TactilePPS22EcCommand::SharedCtor() {
  _cached_size_ = 0;
  dummy_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3TactilePPS22EcCommand::~M3TactilePPS22EcCommand() {
  SharedDtor();
}

void M3TactilePPS22EcCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3TactilePPS22EcCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3TactilePPS22EcCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3TactilePPS22EcCommand_descriptor_;
}

const M3TactilePPS22EcCommand& M3TactilePPS22EcCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tactile_5fpps22_5fec_2eproto();  return *default_instance_;
}

M3TactilePPS22EcCommand* M3TactilePPS22EcCommand::default_instance_ = NULL;

M3TactilePPS22EcCommand* M3TactilePPS22EcCommand::New() const {
  return new M3TactilePPS22EcCommand;
}

void M3TactilePPS22EcCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    dummy_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3TactilePPS22EcCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 dummy = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dummy_)));
          set_has_dummy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3TactilePPS22EcCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 dummy = 1;
  if (has_dummy()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->dummy(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3TactilePPS22EcCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 dummy = 1;
  if (has_dummy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->dummy(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3TactilePPS22EcCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 dummy = 1;
    if (has_dummy()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->dummy());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3TactilePPS22EcCommand::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3TactilePPS22EcCommand* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3TactilePPS22EcCommand*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3TactilePPS22EcCommand::MergeFrom(const M3TactilePPS22EcCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dummy()) {
      set_dummy(from.dummy());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3TactilePPS22EcCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3TactilePPS22EcCommand::CopyFrom(const M3TactilePPS22EcCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3TactilePPS22EcCommand::IsInitialized() const {
  
  return true;
}

void M3TactilePPS22EcCommand::Swap(M3TactilePPS22EcCommand* other) {
  if (other != this) {
    std::swap(dummy_, other->dummy_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3TactilePPS22EcCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3TactilePPS22EcCommand_descriptor_;
  metadata.reflection = M3TactilePPS22EcCommand_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3TactilePPS22EcParam::kConfigFieldNumber;
#endif  // !_MSC_VER

M3TactilePPS22EcParam::M3TactilePPS22EcParam()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3TactilePPS22EcParam::InitAsDefaultInstance() {
}

M3TactilePPS22EcParam::M3TactilePPS22EcParam(const M3TactilePPS22EcParam& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3TactilePPS22EcParam::SharedCtor() {
  _cached_size_ = 0;
  config_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3TactilePPS22EcParam::~M3TactilePPS22EcParam() {
  SharedDtor();
}

void M3TactilePPS22EcParam::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3TactilePPS22EcParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3TactilePPS22EcParam::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3TactilePPS22EcParam_descriptor_;
}

const M3TactilePPS22EcParam& M3TactilePPS22EcParam::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tactile_5fpps22_5fec_2eproto();  return *default_instance_;
}

M3TactilePPS22EcParam* M3TactilePPS22EcParam::default_instance_ = NULL;

M3TactilePPS22EcParam* M3TactilePPS22EcParam::New() const {
  return new M3TactilePPS22EcParam;
}

void M3TactilePPS22EcParam::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    config_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3TactilePPS22EcParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 config = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &config_)));
          set_has_config();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3TactilePPS22EcParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 config = 1;
  if (has_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->config(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3TactilePPS22EcParam::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 config = 1;
  if (has_config()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->config(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3TactilePPS22EcParam::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 config = 1;
    if (has_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->config());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3TactilePPS22EcParam::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3TactilePPS22EcParam* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3TactilePPS22EcParam*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3TactilePPS22EcParam::MergeFrom(const M3TactilePPS22EcParam& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_config()) {
      set_config(from.config());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3TactilePPS22EcParam::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3TactilePPS22EcParam::CopyFrom(const M3TactilePPS22EcParam& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3TactilePPS22EcParam::IsInitialized() const {
  
  return true;
}

void M3TactilePPS22EcParam::Swap(M3TactilePPS22EcParam* other) {
  if (other != this) {
    std::swap(config_, other->config_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3TactilePPS22EcParam::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3TactilePPS22EcParam_descriptor_;
  metadata.reflection = M3TactilePPS22EcParam_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
